---
title: "Case Study 09"
author: Hang Tian
date: "`r Sys.Date()`"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(1) # seed for any random generation
```
# 1. Import packages and get data
```{r}
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
data(world)
data(us_states)
# Download zipped data from noaa with storm track information
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"

tdir=tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir) #unzip the compressed folder
storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))
```
# 2. Data processing
```{r}
storm_cleaned=storm_data%>%filter(ISO_TIME>=1950)%>%
  mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x))%>%
  mutate(decade=(floor(year/10)*10))
region=st_bbox(storm_cleaned)

```
# 3. Plot
```{r}
ggplot(world)+
  geom_sf()+
  stat_bin2d(data=storm_cleaned,aes(y=st_coordinates(storm_cleaned)[,2], x=st_coordinates(storm_cleaned)[,1]),bins=100)+
  facet_wrap(~decade)+
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000))+
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)])
```

# 4. Table calculating
```{r}
us_states=st_transform(us_states,st_crs(storm_cleaned))
temp=us_states%>%select(state=NAME)
storm_states <- st_join(storm_cleaned, temp, join = st_intersects,left = F)
result=storm_states%>%group_by(state)%>%
  summarize(storms=length(unique(NAME)))%>%
  arrange(desc(storms))%>%
  slice(1:5)%>%
  st_drop_geometry()
result
```

